docs/Home.md, docs/compliance/accessories/_category_.json, docs/compliance/accessories/wireless-a8.md, docs/compliance/rock3/_category_.json, docs/compliance/rock3/rock3c.md, docs/compliance/rock4/_category_.json, docs/compliance/rock4/rock4cp.md, docs/compliance/rock5/_category_.json, docs/compliance/rock5/rock5a.md, docs/compliance/rock5/rock5b.md
=> add compliance

docs/rock5/alternative-os/wor.md
modify descriptions of Windows On R
=> update Windows on R document

docs/rock5/alternative-os/fydeos.md
=> Local branch

docs/compliance/rock3/rock3a.md
=> modify rock 3a compliance

docs/compliance/rock5/rock5a.md, docs/compliance/rock5/rock5b.md
=> add rock5 family'S compliance

docs/accessories/lcd-8-hd.md, docs/compliance/accessories/_category_.json, docs/compliance/rock3/_category_.json, docs/compliance/rock4/_category_.json, docs/compliance/rock5/_category_.json
=> modify compliance

docusaurus.config.js, src/css/custom.css, src/pages/index.js
=> Add Search

docs/rock3/rock3c/hardware/_category_.json, docs/rock3/rock3c/hardware/revisions.md, docs/rock5/rock5a/hardware/_category_.json, docs/rock5/rock5b/hardware/_category_.json, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/revisions.md
add hardware information of 3C
```bash
yarn start
```
=> add hardware information of 3C

docs/rock3/rock3c/getting-started/overview.md
=> modify 3C feature: del 8GB ddr

docs/general-tutorial/ssh-access.md, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/apt.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/ssh-access.md, i18n/en/docusaurus-plugin-content-docs/current/radxa-os/rsetup/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/rock3/alternative-os/third-party-images.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/faq.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/faq.md
=> New add en files about apt,ssh-access,third-party-images, and modified ssh-access

i18n/en/code.json, i18n/zh/code.json, src/pages/index.js
=> title change

docs/Home.md, src/utils/getPriducts.js
Duplicate problem with changing category selection
=> Home category duplication issue

docs/rock3/rock3c/hardware/rock3c-gpio.md, docs/rock5/rock5b/hardware/rock5b-gpio.md
=> update 3C 5B GPIO table style

i18n/en/docusaurus-theme-classic/footer.json, i18n/en/docusaurus-theme-classic/navbar.json, i18n/zh/docusaurus-theme-classic/footer.json, i18n/zh/docusaurus-theme-classic/navbar.json
Services Chinese and English switch
=> Services Chinese and English switch

docs/general-tutorial/image-backup.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/image-backup.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rk-dev-tool.md
=> add general tutorial

docs/general-tutorial/rk-dev-tool.md
将链接更新为默认中文的包
```bash
yarn start
```
=> update RKDevTool download link

docusaurus.config.js
=> Sidebar auto-collapse

docs/rock5/official-images.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/official-images.md
=> add official images docs for ROCK 5 series

i18n/en/docusaurus-plugin-content-docs/current/rock5/official-images.md
=> modify official images en

i18n/en/docusaurus-theme-classic/navbar.json, i18n/zh/docusaurus-theme-classic/navbar.json, src/css/custom.css
Table reduced, translation welcome
=> Table reduced, translation welcome

docs/rock5/official-images.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/official-images.md
1. 更新ROCK 5B镜像到B36
2. 修复若干格式问题
- 结尾多余空格
- 中文标点出现在英文文档里
- note和tip有专门的语法
- 拼写及翻译错误
- 文章标题与文件名不符
- 通用部分出现特定产品的内容 
```bash
yarn start
```
=> Update ROCK 5 Official Images page

docs/rock5/rock5a/hardware/rock5a-gpio.md
=> update ROCK 5A gpio docs

docs/rock5/rock5b/hardware/revisions.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/hardware/revisions.md
=> add ROCK 5B hardware version history and design documents

docs/rock5/official-images.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/official-images.md
=> update some paragraph format of ROCK 5 official images

.github/PULL_REQUEST_TEMPLATE.md
Update the review guide to more easily track new changes.
```bash
yarn start
```
=> Update review guide

docs/rock5/faq.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/faq.md
```bash
yarn start
kill %1
```
=> update ZH ROCK 5 FAQ and add EN ROCK 5 FAQ

docs/rock3/rock3c/getting-started/overview.md, docs/rock5/rock5a/getting-started/overview.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/rock3c-gpio.md
```bash
yarn start
kill %1
```
=> update ROCK 3C overview ZH add EN version

docs/general-tutorial/os-installation.md, docs/rock3/official-images.md, docs/rock5/rock5b/getting-started/before-start.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/os-installation.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/official-images.md
把之前Etcher的下载链接改为官网链接
```bash
yarn start
kill %1
```
=> update Etcher link

docs/general-tutorial/apt.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/apt.md
```bash
yarn start
kill %1
```
=> fixed code block

docs/rock3/rock3c/getting-started/overview.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/products.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
```bash
yarn start
kill %1
```
=> update 3C overview: 4k@60 -> 1920x1080@60

docs/rock5/rock5b/accessories-guides/heatsink-4012.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories-guides/heatsink-4012.md
```bash
yarn start
kill %1
```
=> 修改 5B 风扇使用描述错误及盘古之白

docs/general-tutorial/_category_.json, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/_category_.json
```bash
yarn start
kill %1
```
=> add some sidebar translation

docs/rock3/rock3c/getting-started/before-start.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/before-start.md
```bash
yarn start
kill %1
```
=> add before-start of 3C

docs/rock4/hardware/_category_.json, docs/rock4/hardware/download.md, docs/rock4/hardware/rock4-gpio.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/hardware/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/rock4/hardware/download.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/hardware/rock4-gpio.md
```bash
yarn start
kill %1
```
=> Create Hardware Information of ROCK 4 Series

docs/rock4/rock4c+/getting-started/overview.md, docs/rock4/rock4c+/hardware/rock4c+-gpio.md, docs/rock4/rock4se/getting-started/overview.md, docs/rock4/rock4se/hardware/rock4se-gpio.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4c+/getting-started/overview.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4c+/hardware/rock4c+-gpio.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4se/getting-started/overview.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4se/hardware/rock4se-gpio.md
```bash
yarn start
kill %1
```
=> Update the GPIO link on ROCK 4SE 4C+ overview and del redundant file

docs/compliance/rock3/_category_.json, docs/compliance/rock4/_category_.json, docs/compliance/rock5/_category_.json, i18n/en/docusaurus-plugin-content-docs/current.json
```bash
yarn start
kill %1
```
=> update ROCK Series compliance titles

docs/rock5/rock5a/accessories-guides/penta-sata-hat.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/accessories-guides/penta-sata-hat.md
update rock5a penta usage.
```bash
yarn start
kill %1
```
=> update rock5a penta usage

docs/rock3/rock3a/hardware/_category_.json
```bash
yarn start
kill %1
```
=> translate ROCK 3A hardware category

i18n/en/docusaurus-plugin-content-docs/current.json
```bash
yarn start
kill %1
```
=> add Peripheral Configuration translation

docs/rock3/rock3a/hardware/download.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/hardware/download.md
```bash
yarn start
kill %1
```
=> add ROCK 3A hardware information download

docs/rock4/rock4se/getting-started/before-start.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4se/getting-started/before-start.md
```bash
yarn start
kill %1
```
=> add ROCK 4SE before-start

docs/compliance/compute-module/radxa-cm3.md, i18n/en/docusaurus-plugin-content-docs/current/compliance/compute-module/radxa-cm3.md
```bash
yarn start
kill %1
```
=> add cm3 compliance

docs/compliance/rock3/rock3c.md, i18n/en/docusaurus-plugin-content-docs/current/compliance/rock3/rock3c.md
```bash
yarn start
kill %1
```
=> add rock3c compliance

docs/rock4/rock4c+/getting-started/before-start.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4c+/getting-started/before-start.md
```bash
yarn start
kill %1
```
=> add ROCK 4C+ before start

docs/compliance/rock4/rock4cp.md, i18n/en/docusaurus-plugin-content-docs/current/compliance/rock4/rock4cp.md
```bash
yarn start
kill %1
```
=> new add 4c+ compliance

docs/rock4/hardware/revisions.md, i18n/en/docusaurus-plugin-content-docs/current.json
```bash
yarn start
kill %1
```
=> Fix up two issues

.github/workflows/deploy.yaml
```bash
yarn start
kill %1
```
=> Disable code deployment for merge_group check

docs/rock5/rock5b/accessories-guides/ssd-adaptation.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories-guides/ssd-adaptation.md
```bash
yarn start
kill %1
```
=> add ROCK 5B SSD Compatibility

docusaurus.config.js
=> Synchronizing the Radxa homepage navigation bar

docs/general-tutorial/rksdk/rkdeveloptool.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/rkdeveloptool.md
```bash
yarn start
kill %1
```
=> Fix rkdeveloptool compiling errors

.github/workflows/deploy.yaml, docs/rock5/lowlevel-development/bootloader_spi_flash.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/getting-started/rkdevtool.md
Various mistakes in formatting and listing.
@Maycides please review this ASAP. I need to send the updated link to a customer.
```bash
yarn start
kill %1
```
=> Fix documentation issues

src/pages/index.module.css
=> Home page filler issue fixed

docs/general-tutorial/rknn-toolkit-lite2.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rknn-toolkit-lite2.md
关联 #204 
modified:   i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rknn-toolkit-lite2.md
modified:   docs/current/general-tutorial/rknn-toolkit-lite2.md
```bash
yarn start
kill %1
```
=> 更新RKNN Toolkit Lite2教程

.github/workflows/deploy.yaml
```bash
yarn start
kill %1
```
=> Fix CI no error issue

docs/compliance/compute-module/_category_.json, docs/compute-module/_category_.json, i18n/en/docusaurus-plugin-content-docs/current.json
```bash
yarn start
kill %1
```
=> fix description of Compute module

docs/Home.md
```bash
yarn start
kill %1
```
=> update home page CM description

docs/zero/zero3w/getting-started/before-start.md, docs/zero/zero3w/hardware/_category_.json, docs/zero/zero3w/hardware/zero3w-gpio.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3w/getting-started/before-start.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3w/hardware/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3w/hardware/zero3w-gpio.md
```bash
yarn start
kill %1
```
=> add zero 3w docs

docs/accessories/emmc_reader.md
```bash
yarn start
kill %1
```
=> emmc reader: fix typo

docs/Home.md
```bash
yarn start
kill %1
```
=> Add zero series dropdown box

docs/rock3/rock3c/hardware/rock3c-gpio.md, docs/zero/zero3w/hardware/zero3w-gpio.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/rock3c-gpio.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3w/hardware/zero3w-gpio.md
Delete CAN of 3C, ZERO 3W GPIO
```bash
yarn start
kill %1
```
=> Delete CAN on RK3566 GPIO

i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/getting-started/overview.md
```bash
yarn start
kill %1
```
=> replace the close look picture to Annotation Diagram of 3A  in overview.md

.pre-commit-config.yaml, README.md, yarn.lock
```bash
yarn start
kill %1
```
=> Update dependencies and add pre-commit instruction

docs/android/overview.md, docs/yocto/_category_.json, docs/yocto/overview.md, i18n/en/docusaurus-plugin-content-docs/current/android/overview.md, i18n/en/docusaurus-plugin-content-docs/current/yocto/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/yocto/overview.md
```bash
yarn start
kill %1
```
=> Add android and yocto folder

docs/android/_category_.json, docs/yocto/_category_.json
```bash
yarn start
kill %1
```
=> Modify descriptions of android and yocto

docs/android/_category_.json, docs/radxa-os/_category_.json, docs/yocto/_category_.json, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-plugin-content-docs/current/android/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/radxa-os/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/yocto/_category_.json
```bash
yarn start
kill %1
```
=> Change the position of OS

docs/rock3/rock3a/getting-started.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/getting-started.md
```bash
yarn start
kill %1
```
=> change the hardware content to link in getting-started.md

docs/rock3/rock3a/getting-started.md
```bash
yarn start
kill %1
```
=> change the gpio info page's path to an relative path

docs/zero/images.md, docs/zero/official-images.md, docs/zero/zero2pro/getting-started/getting-start.md, i18n/en/docusaurus-plugin-content-docs/current/zero/images.md, i18n/en/docusaurus-plugin-content-docs/current/zero/official-images.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/getting-started/getting-start.md
```bash
yarn start
kill %1
```
=> Update Zero series images download docs

docs/rock3/rock3b/_category_.json, docs/rock3/rock3b/hardware/_category_.json, docs/rock3/rock3b/hardware/rock3b-gpio.md, i18n/en/code.json, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/hardware/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/hardware/rock3b-gpio.md, i18n/en/docusaurus-theme-classic/footer.json, i18n/en/docusaurus-theme-classic/navbar.json
```bash
yarn start
kill %1
```
=> add Radxa ROCK 3B GPIO pinout

docs/rock3/rock3a/maskrom.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/maskrom.md
```bash
yarn start
kill %1
```
=> add supplementary note of 3A maskrom doc

docs/compute-module/nx5/_category_.json, docs/compute-module/nx5/hardware/_category_.json, docs/compute-module/nx5/hardware/nx5-io-gpio.md, i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/hardware/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/hardware/nx5-io-gpio.md
```bash
yarn start
kill %1
```
=> add Radxa NX5 GPIO pinout

docs/general-tutorial/os-installation.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/os-installation.md
```bash
yarn start
kill %1
```
=> Add another method of flashing os

docs/rock3/rock3b/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/_category_.json
```bash
yarn start
kill %1
```
=> del category of 3B

docs/general-tutorial/rksdk/loader.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/loader.md
```bash
yarn start
kill %1
```
=> list the cpu models for the loader

docs/general-tutorial/rksdk/loader.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/loader.md
```bash
yarn start
kill %1
```
=> Update Tip messge style in loader.md

docs/rock3/rock3c/getting-started/overview.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/getting-started.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
```bash
yarn start
kill %1
```
=> modify DDR descriptions

docs/nio/nio12l/readme.md, docs/nio/readme.md
```bash
yarn start
kill %1
```
=> Re-organise NIO series documents structure

docs/zero/zero2pro/getting-started/getting-start.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/getting-started/getting-start.md
据QQ群反馈，原链接是404
```bash
yarn start
kill %1
```
=> fix radxa zero 2 pro loader download link

docs/rock3/rock3b/hardware/download.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/hardware/download.md
```bash
yarn start
kill %1
```
=> add rock 3b hardware data download

docs/rock3/images.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/images.md
```bash
yarn start
kill %1
```
=> Add rock 3b image download

docs/rock3/rock3b/hardware/download.md
```bash
yarn start
kill %1
```
=> ROCK 3B HW Download page clean

i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/hardware/download.md
```bash
yarn start
kill %1
```
=> Update 3B 3D files download EN

docs/rock5/alternative-os/5a-3rd-images.md
```bash
yarn start
kill %1
```
=> update 5A 3rd images title

docs/compliance/radiofrequency-guidance/pre-env.md, i18n/en/docusaurus-plugin-content-docs/current/compliance/radiofrequency-guidance/pre-env.md
```bash
yarn start
kill %1
```
=> add rtl8723 fixed frequency guide

src/css/custom.css, src/pages/index.module.css
```bash
yarn start
kill %1
```
=> Adjust the font size on mobile

contributors.py
```bash
yarn start
kill %1
```
=> fix contributors.py

docs/zero/zero3/README.md, docs/zero/zero3/accessories/README.md, docs/zero/zero3/application-configuration/README.md, docs/zero/zero3/application-development/README.md, docs/zero/zero3/getting-started/README.md, docs/zero/zero3/hardware-development/README.md, docs/zero/zero3/lowlevel-development/README.md, docs/zero/zero3/other-os/README.md, docs/zero/zero3/other-os/android/README.md, docs/zero/zero3/system-configuration/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/application-configuration/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/application-development/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/hardware-development/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/lowlevel-development/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/android/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/system-configuration/README.md
```bash
yarn start
kill %1
```
=> update ZERO 3's OverViews

docs/Home.md, src/css/custom.css
```bash
yarn start
kill %1
```
=> fix sidebar hidden

i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/android/remote-login.md
```bash
yarn start
kill %1
```
=> fix pic doesn't show correctly under zero3

src/utils/docs.js
```bash
yarn start
kill %1
```
=> add section function

docs/zero/zero3/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/README.md
```bash
yarn start
kill %1
```
=> fix zero3 overview typo

docs/radxa-os/development/panfork.md, i18n/en/docusaurus-plugin-content-docs/current/radxa-os/development/panfork.md
Modify panfork build dependencies
```bash
yarn start
kill %1
```
=> Modify panfork build dependencies

src/utils/docs.js
```bash
yarn start
kill %1
```
=> add image component

docs/common/general/_serial.mdx, docs/zero/zero3/low-level-dev/serial.md, i18n/en/docusaurus-plugin-content-docs/current/common/general/_serial.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/low-level-dev/serial.md
```bash
yarn start
kill %1
```
=> common add serail

src/utils/docs.js
```bash
yarn start
kill %1
```
=> modify section component

docs/common/general/_serial.mdx, docs/zero/zero3/low-level-dev/serial.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/low-level-dev/serial.md
```bash
yarn start
kill %1
```
=> modify serial

docs/common/general/_serial.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/general/_serial.mdx
```bash
yarn start
kill %1
```
=> modify serial using section

docs/common/general/_boot-media.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/general/_boot-media.mdx
```bash
yarn start
kill %1
```
=> common add boot media

docs/zero/zero3/README.md, docs/zero/zero3/getting-started/accessory-usage.md, docs/zero/zero3/getting-started/download.md, docs/zero/zero3/low-level-dev/install-os-on-emmc.md, docs/zero/zero3/other-os/android/install-os.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/accessory-usage.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/low-level-dev/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/low-level-dev/install-os-on-emmc.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/android/install-os.md
```bash
yarn start
kill %1
```
=> update tab's value of zero3

docs/common/dev/_rknn-toolkit2.mdx, docs/common/general/_boot-media.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rknn-toolkit2.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/general/_boot-media.mdx
```bash
yarn start
kill %1
```
=> common add rknn-toolkit2

docs/common/dev/_mraa.mdx, docs/zero/zero3/app-development/mraa.md, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_mraa.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/app-development/mraa.md
```bash
yarn start
kill %1
```
=> move mraa from radxa-os to common

docs/zero/zero3/getting-started/install-os.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/install-os.md
```bash
yarn start
kill %1
```
=> use image component

docs/common/general/_etcher.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/general/_etcher.mdx, src/utils/docs.js
```bash
yarn start
kill %1
```
=> modify image args

docs/common/general/_etcher.mdx, docs/zero/zero3/getting-started/install-os.md, i18n/en/docusaurus-plugin-content-docs/current/common/general/_etcher.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/install-os.md
```bash
yarn start
kill %1
```
=> modify _serial

i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/README.md
```bash
yarn start
kill %1
```
=> change the sidebar title of zero3

docs/zero/zero2pro/getting-started/getting-start.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/getting-started/getting-start.md
```bash
yarn start
kill %1
```
=> zero2pro use _etcher

docs/common/general/_loader.mdx, docs/compute-module/cm3i/install-debian-system.md, docs/compute-module/cm3i/loader.md, docs/general-tutorial/rksdk/rkdeveloptool.md, docs/general-tutorial/rksdk/rkdevtool.md, docs/general-tutorial/rksdk/upgrade_tool.md, i18n/en/docusaurus-plugin-content-docs/current/common/general/_loader.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-debian-system.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/loader.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/rkdeveloptool.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/rkdevtool.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/upgrade_tool.md
```bash
yarn start
kill %1
```
=> use _loader mdx

docs/common/dev/_mpp.mdx, docs/general-tutorial/rksdk/README.md, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_mpp.mdx, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/README.md
```bash
yarn start
kill %1
```
=> mv rksdk/mpp to common

docs/zero/zero2pro/low-level-dev/serial.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/low-level-dev/serial.md
```bash
yarn start
kill %1
```
=> fix zero2pro serial

docs/common/dev/_upgrade-tool.mdx, docs/common/general/_install-os.mdx, docs/compute-module/cm3i/install-debian-system.md, docs/compute-module/cm3i/low-level-dev/upgrade-tool.md, docs/compute-module/cm5/cm5-io-board/cm5io-maskrom-mode.md, docs/compute-module/cm5/low-level-dev/upgrade-tool.md, docs/compute-module/nx5/install_os.md, docs/compute-module/nx5/low-level-dev/upgrade-tool.md, docs/general-tutorial/rksdk/README.md, docs/rock3/rock3c/getting-started/3c-maskrom.md, docs/rock3/rock3c/low-level-dev/upgrade-tool.md, docs/zero/zero3/low-level-dev/upgrade-tool.md, docs/zero/zero3/other-os/android/install-os.md, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_upgrade-tool.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/general/_install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-debian-system.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/low-level-dev/upgrade-tool.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/cm5-io-board/cm5io-maskrom-mode.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/low-level-dev/upgrade-tool.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/install_os.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/low-level-dev/upgrade-tool.md, i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rksdk/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/3c-maskrom.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/low-level-dev/upgrade-tool.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/low-level-dev/upgrade-tool.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/android/install-os.md
```bash
yarn start
kill %1
```
=> mv rksdk/upgrade-tool to common

docs/compute-module/nx5/install_os.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/install_os.md
```bash
yarn start
kill %1
```
=> clean nx5 install_os

docs/x/x2l/getting-started.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/getting-started.md
```bash
yarn start
kill %1
```
=> Fix warning syntax error

docs/compute-module/nx5/README.md, docs/compute-module/nx5/getting-started/install-os.mdx, docs/compute-module/nx5/radxa-os/install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/README.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/getting-started/install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/install-os.mdx
```bash
yarn start
kill %1
```
=> nx5: update

i18n/en/docusaurus-plugin-content-docs/current/rock3/e25/accessories/pd_30w.md
```bash
yarn start
kill %1
```
=> update e25 radxa pd30w english docs

docs/Home.md, docs/compute-module/nx5/getting-started/download.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/getting-started/download.md
```bash
yarn start
kill %1
```
=> nx5: Change homepage product index and mirror address

docs/common/general/_install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/general/_install-os.mdx
```bash
yarn start
kill %1
```
=> modify install-os mdx

i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/serial.md
```bash
yarn start
kill %1
```
=> rock5b add serial

docs/radxa-os/development/rknn-toolkit-lite2.md, i18n/en/docusaurus-plugin-content-docs/current/radxa-os/development/rknn-toolkit-lite2.md
```bash
yarn start
kill %1
```
=> fix rknn-toolkit-lite

docs/nio/readme.md, i18n/en/docusaurus-plugin-content-docs/current/nio/readme.md
```bash
yarn start
kill %1
```
=> modify NIO label

docs/notice.md, i18n/en/docusaurus-plugin-content-docs/current/notice.md
```bash
yarn start
kill %1
```
=> modify notice label

i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/README.md
```bash
yarn start
kill %1
```
=> add rock5b low-level-dev readme

docs/rock3/images.md, docs/zero/images.md, docs/zero/zero3/getting-started/download.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/images.md, i18n/en/docusaurus-plugin-content-docs/current/zero/images.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md
```bash
yarn start
kill %1
```
=> update rock3c and zero3 image

i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/low-level-dev/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/low-level-dev/README.md
```bash
yarn start
kill %1
```
=> add rock3 low-level-dev readme

docs/compute-module/images.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/images.md
```bash
yarn start
kill %1
```
=> update cm3 io images download url

docs/compute-module/nx5/radxa-os/low-level-dev/kernel.md, docs/compute-module/nx5/radxa-os/low-level-dev/u-boot.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/low-level-dev/kernel.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/low-level-dev/u-boot.md
```bash
yarn start
kill %1
```
=> nx5 io: update kernel and u-boot develop

docs/rock3/rock3a/low-level-dev/README.md, docs/rock3/rock3b/low-level-dev/README.md
```bash
yarn start
kill %1
```
=> add rock3 low-level-dev readme zh

docs/rock5/rock5b/hardware/hardware-details.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/hardware/hardware-details.md
```bash
yarn start
kill %1
```
=> Update 5B power support list

docs/x/x2l/README.md, docs/x/x2l/software/README.md, docs/x/x2l/software/Roobi.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/README.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/software/README.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/software/Roobi.md
```bash
yarn start
kill %1
```
=> add x2l roobi documents

src/components/CustomDocItem/Layout/index.js
```bash
yarn start
kill %1
```
=> add TOC when importing mdx

src/components/CustomDocItem/Layout/index.js, src/components/CustomDocItem/Layout/styles.module.css
```bash
yarn start
kill %1
```
=> modify toc-mobile

docs/rock5/rock5b/hardware/hardware-details.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/hardware/hardware-details.md
```bash
yarn start
kill %1
```
=> Update 5B power descriptions part 2

docs/compute-module/cm5/radxa-os/install-os.mdx
```bash
yarn start
kill %1
```
=> fix broken links

docs/Home.md
```bash
yarn start
kill %1
```
=> Home: add CM5 guide

src/utils/docs.js
```bash
yarn start
kill %1
```
=> add details component

docs/compute-module/nx5/getting-started/preparation.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/getting-started/preparation.md
Use links instead of references
=> nx5: Updated documentation for the preparation section

docs/rock3/e25/os-config/README.md, docs/rock3/rock3a/os-config/README.md, docs/rock3/rock3b/os-config/README.md, docs/rock3/rock3c/os-config/README.md, docs/rock4/os-config/README.md, docs/rock5/rock5a/os-config/README.md, docs/rock5/rock5b/os-config/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/e25/os-config/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/os-config/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/os-config/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/os-config/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/os-config/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/os-confiig/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/os-config/README.md
```bash
yarn start
kill %1
```
=> add os-config README

docs/common/radxa-os/_audio.mdx, docs/zero/zero3/radxa-os/audio.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_audio.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/audio.md
```bash
yarn start
kill %1
```
=> zero3 add audio management

docs/common/radxa-os/_autologin.mdx, docs/zero/zero3/radxa-os/autologin.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_autologin.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/autologin.md
```bash
yarn start
kill %1
```
=> zero3 add autologin

docs/x/roobi/install-roobi.md
```bash
yarn start
kill %1
```
=> fix tip error

docs/common/radxa-os/_display.mdx, docs/zero/zero3/radxa-os/display.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_display.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/display.md
```bash
yarn start
kill %1
```
=> zero3 add display setting

docs/compute-module/nx5/radxa-os/app-dev/README.md, docs/compute-module/nx5/radxa-os/app-dev/mraa.md, docs/compute-module/nx5/radxa-os/app-dev/wiringx.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/app-dev/README.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/app-dev/mraa.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/app-dev/wiringx.md
```bash
yarn start
kill %1
```
=> update NX5 mraa, remove wiringX

docs/common/radxa-os/_headless.mdx, docs/zero/zero3/radxa-os/headless.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_headless.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/headless.md
```bash
yarn start
kill %1
```
=> zero3 add headless mode

docs/common/radxa-os/_office.mdx, docs/zero/zero3/radxa-os/office.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_office.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/office.me
```bash
yarn start
kill %1
```
=> zero add office

docs/common/radxa-os/_locale.mdx, docs/zero/zero3/radxa-os/locale.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_locale.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/locale.md
```bash
yarn start
kill %1
```
=> zero3 add locale

docs/common/radxa-os/_usbnet.mdx, docs/zero/zero3/radxa-os/usbnet.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_usbnet.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/usbnet.md
```bash
yarn start
kill %1
```
=> zero3 add usb network

docs/common/radxa-os/_social.mdx, docs/zero/zero3/radxa-os/social.md, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_social.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/radxa-os/social.md
```bash
yarn start
kill %1
```
=> zero3 add social apps

docs/rock5/rock5b/low-level-dev/rknn-toolkit2.md, docs/rock5/rock5b/low-level-dev/serial.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/rknn-toolkit2.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/serial.md
```bash
yarn start
kill %1
```
=> add rknn-tool-kit doc

docs/compute-module/nx5/android/README.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/android/README.md
```bash
yarn start
kill %1
```
=> modify android document structure

docs/compute-module/cm3/cm3-io-board/pinout.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/cm3-io-board/pinout.md
Signed-off-by: Nascs Fang <nascs@radxa.com>
```bash
yarn start
kill %1
```
=> radxa cm3 io: fix pin 26

docs/common/dev/_rtsp.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rtsp.mdx
```bash
yarn start
kill %1
```
=> modify common rtsp

docs/common/dev/_panfork.mdx, docs/zero/zero3/app-development/panfork.md, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_panfork.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/app-development/panfork.md
```bash
yarn start
kill %1
```
=> zero3 add panfork

docs/common/dev/_hdmi-rx.mdx, docs/rock5/rock5b/app-development/README.md, docs/rock5/rock5b/app-development/hdmi-rx.md, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_hdmi-rx.mdx, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/app-development/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/app-development/hdmi-rx.md
```bash
yarn start
kill %1
```
=> rock5b add hdmi-rx

docs/common/config/_rsetup.mdx, docs/common/config/rsetup/_disable-fiq.mdx, docs/common/dev/_hdmi-rx.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/config/rsetup/_disable-fiq.mdx
```bash
yarn start
kill %1
```
=> rsetup add disable-fiq

i18n/en/docusaurus-plugin-content-docs/current/rock3/e25/os-config/bootparam.md
```bash
yarn start
kill %1
```
=> e25 add bootparam

docs/compute-module/nx5/getting-started/download.md, docs/compute-module/nx5/hardware/hw-interface.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/getting-started/download.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/hardware/hw-interface.md
```bash
yarn start
kill %1
```
=> NX5: Supplemental hardware-related schematic download links and hardware interface descriptions

docs/x/x2l/README.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/README.md
```bash
yarn start
kill %1
```
=> docs: modify x2l README

i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_backup-os.mdx
```bash
yarn start
kill %1
```
=> en: fix backup typo

docs/compute-module/cm3/mp-deployment/backup.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/mp-deployment/backup.md
```bash
yarn start
kill %1
```
=> cm3 add backup

docs/x/x2l/software-development/c_sdk_examples.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/software-development/c_sdk_examples.md
Signed-off-by: Nascs Fang <nascs@radxa.com>
```bash
yarn start
kill %1
```
=> feat: add pico-sdk & pico-example tutorials

docs/common/radxa-os/_apt-repo.mdx, docs/common/radxa-os/_audio.mdx, docs/common/radxa-os/_display.mdx, docs/common/radxa-os/_headless.mdx, docs/common/radxa-os/_locale.mdx, docs/common/radxa-os/_office.mdx, docs/common/radxa-os/_remote-access.mdx, docs/common/radxa-os/_social.mdx, docs/common/radxa-os/_usbnet.mdx, docs/common/radxa-os/_video.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_apt-repo.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_audio.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_display.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_headless.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_locale.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_office.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_remote-access.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_social.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_usbnet.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_video.mdx
```bash
yarn start
kill %1
```
=> fix common/radxa-os bash style

docs/x/x2l/software-development/uart.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/uart.md
```bash
yarn start
kill %1
```
=> feat: add uart communication for radxa x2l

docs/compute-module/cm5/cm5-io-board/README.md, docs/compute-module/cm5/cm5-io-board/pinout.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/cm5-io-board/README.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/cm5-io-board/pinout.md
```bash
yarn start
kill %1
```
=> feat: Add Radxa CM5 IO GPIO pinout

docs/common/radxa-os/_backup-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_backup-os.mdx
```bash
yarn start
kill %1
```
=> add: backup-os docs

docs/common/dev/_rknn-toolkit2.mdx, docs/rock5/rock5b/low-level-dev/rknn-toolkit2.md, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rknn-toolkit2.mdx, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/rknn-toolkit2.md
```bash
yarn start
kill %1
```
=> fix: rock5b rknn typo

docs/common/general/_install-os.mdx, docs/zero/zero/install-os.md, i18n/en/docusaurus-plugin-content-docs/current/common/general/_install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/zero/zero/install-os.md
```bash
yarn start
kill %1
```
=> feat: common install-os using section

docs/rock5/rock5a/radxa-os/README.md, docs/rock5/rock5a/radxa-os/using-apt.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/radxa-os/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/radxa-os/using-apt.md
```bash
yarn start
kill %1
```
=> feat: rock5a add apt

docs/accessories/radxa-23w-poe.md, i18n/en/docusaurus-plugin-content-docs/current/accessories/radxa-23w-poe.md
```bash
yarn start
kill %1
```
=> remove tab in the 23w poe page

docs/zero/zero3/accessories/3e-poe-hat.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/accessories/3e-poe-hat.md
```bash
yarn start
kill %1
```
=> docs: update radxa zero 3e poe hat

docs/rock3/application-development/README.md, docs/rock3/e25/README.md, docs/rock3/faq.md, docs/rock3/images.md, docs/rock3/lowlevel-development/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/application-development/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/e25/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/faq.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/images.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/lowlevel-development/README.md
```bash
yarn start
kill %1
```
=> fix: update sorting of radxa rock 3 series

.github/CODEOWNERS, .gitownrc, .pre-commit-config.yaml
* fixes https://github.com/radxa-docs/documentation/issues/596
Previously on #598
```bash
yarn start
kill %1
```
=> feat: add CODEOWNERS

docs/rock5/rock5a/hardware/rock5a-gpio.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/hardware/rock5a-gpio.md
```bash
yarn start
kill %1
```
=> radxa rock 5a: add v1.1 gpio pinout support

.cz.toml, .github/CODEOWNERS, .github/workflows/deploy.yaml, .pre-commit-config.yaml
* close https://github.com/radxa-docs/pre-commit-hooks/issues/4
* close https://github.com/radxa-docs/pre-commit-hooks/issues/5
```bash
yarn start
kill %1
```
=> Add commit check

.github/CODEOWNERS, .gitownrc
```bash
yarn start
kill %1
```
=> fix: add more file codeowner by pre-commit run -a

.github/CODEOWNERS, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/os-config/rsetup.md
```bash
yarn start
kill %1
```
=> fix: en: zero3 os-config rsetup

.github/CODEOWNERS, .pre-commit-config.yaml
* close https://github.com/radxa-docs/pre-commit-hooks/issues/6
```bash
yarn start
kill %1
```
=> feat: add pre-commit check check-chinese and change rev

.github/CODEOWNERS, docs/x/x2l/software-development/c_sdk_examples.md, i18n/en/docusaurus-plugin-content-docs/current/x/x2l/software-development/c_sdk_examples.md
Signed-off-by: Nascs Fang <nascs@radxa.com>
```bash
yarn start
kill %1
```
=> fix: fix warning

.github/CODEOWNERS, .pre-commit-config.yaml, i18n/en/docusaurus-plugin-content-docs/current/productlist.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/heatsink-4012.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/accessory-usage.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/bootloader_spi_flash.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/other-os/android/low-level-dev.md
* fixes https://github.com/radxa-docs/documentation/pull/611 CI check error
```bash
yarn start
kill %1
```
=> fix: add gitown stages

.github/CODEOWNERS, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/display_use.md
```bash
yarn start
kill %1
```
=> fix: fix display installation pictures

.github/CODEOWNERS, docs/common/radxa-os/_remote-access.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_remote-access.mdx
```bash
yarn start
kill %1
```
=> feat: _remote-access.mdx: add TeamViewer

.github/CODEOWNERS, .github/workflows/deploy.yaml, .pre-commit-config.yaml
```bash
yarn start
kill %1
```
=> fix: gitown: change stages

docs/accessories/camera_4k.md, i18n/en/docusaurus-plugin-content-docs/current/accessories/camera_4k.md
```bash
yarn start
kill %1
```
=> perf: add camera 4K datasheet

docs/common/dev/_gpiod.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_gpiod.mdx
```bash
yarn start
kill %1
```
=> perf: add gpiod convert way

.github/CODEOWNERS, docs/compute-module/nx5/android/low-level-dev.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/android/low-level-dev.md
```bash
yarn start
kill %1
```
=> fix: fix nx5 android compile step

.github/CODEOWNERS, docs/rock4/FAQ.md, i18n/en/docusaurus-plugin-content-docs/current/rock4/FAQ.md
```bash
yarn start
kill %1
```
=> Add FAQ about ROCK 4B inconsistent memory issue

docs/rock3/rock3a/README.md, i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/README.md
```bash
yarn start
kill %1
```
=> fix: fix features info of radxa rock 3a

.github/CODEOWNERS, docs/compute-module/cm5/radxa-os/app-dev/mraa.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/app-dev/mraa.md
```bash
yarn start
kill %1
```
=> feat: add mraa support for Radxa CM5

docs/common/config/_rsetup.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx
```bash
yarn start
kill %1
```
=> fix: remove annoying warnings from rsetup
